name: Deploy to Firebase Hosting

on:
  push:
    branches: [main]  # deploys on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project url-encoder-decoder --token ${{ secrets.FIREBASE_TOKEN }}
